version: '3.8'

services:
  mysql:
    build: ./mysql
    environment:
      MYSQL_ROOT_PASSWORD: Canada
      MYSQL_DATABASE: mibase1
    ports:
      - "3306:3306"
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - mysql
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - mynetwork

  cypress:
      image: cypress/included:latest  # Usa la versión más reciente de Cypress incluida
      environment:
        - CYPRESS_baseUrl=http://frontend:4200/  # La URL base de la aplicación frontend (puede ser diferente según tu configuración)
      depends_on:
        - frontend  # Asegura que el frontend esté listo antes de ejecutar las pruebas
      networks:
        - mynetwork
      volumes:
        - ./cypress:/e2e  # Volumen para montar tu código de pruebas Cypress (si tienes las pruebas localmente)
      entrypoint: ["sh", "-c", "sleep 90 && npx cypress run; if [ $? -ne 0 ]; then ./commit_screenshots.sh; fi"]

      working_dir: /e2e  # Directorio donde se encuentran las pruebas de Cypress dentro del contenedor
      # Se puede agregar `command` si se necesita configurar más opciones de Cypress, como headless o sin GUI.

networks:
  mynetwork:
    driver: bridge
