name: Build and Test with Docker Compose

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:latest
        env:
          MYSQL_ROOT_PASSWORD: Canada
          MYSQL_DATABASE: mibase1
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --silent" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Paso 1: Instalar Java (para el backend)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adoptopenjdk'

    # Paso 2: Instalar Node.js (para el frontend)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Ajusta según tu versión de Node.js

    # Paso 3: Instalar dependencias del backend (mvn clean install)
    - name: Build backend with Maven
      run: |
        cd backend
        mvn clean install
        mvn clean package
        cd ..

    # Paso 4: Instalar dependencias y construir el frontend
    - name: Build frontend
      run: |
        cd frontend
        export NODE_OPTIONS=--openssl-legacy-provider
        npm install
        npm run build
        cd ..

    # Paso 5: Instalar Angular CLI globalmente
    - name: Install Angular CLI
      run: |
        npm install -g @angular/cli

    # Paso 6: Construir contenedores con Docker Compose
    - name: Build and run Docker Compose
      run: |
        docker-compose -f docker-compose.yml up --build -d

    # Paso 7: Esperar a que la aplicación se inicie
    - name: Wait for the application to be ready
      run: |
        sleep 30  # Espera para asegurar que los contenedores estén listos

    # Paso 8: Ejecutar pruebas de Cypress
    - name: Run Cypress Tests
      run: |
        docker-compose -f docker-compose.yml exec cypress npx cypress run --headless --no-exit
    
    # Paso 9: Detener y eliminar contenedores
    - name: Stop and remove containers
      run: |
        docker-compose -f docker-compose.yml down
